# Generated by Django 4.2.7 on 2023-11-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('day', models.CharField(max_length=9)),
                ('dayWeather', models.CharField(max_length=30)),
                ('nightWeather', models.CharField(max_length=30)),
                ('dayTemperature', models.IntegerField(default=10)),
                ('nightTemperature', models.IntegerField(default=10)),
                ('humidity', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('hour', models.CharField(max_length=4)),
                ('weatherType', models.CharField(max_length=30)),
                ('temperature', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('currentWeather', models.CharField(max_length=30)),
                ('instantTemperature', models.IntegerField(default=10)),
                ('dayTemperature', models.IntegerField(default=10)),
                ('nightTemperature', models.IntegerField(default=10)),
                ('feelsLike', models.IntegerField(default=10)),
                ('humidity', models.IntegerField(default=10)),
            ],
        ),
    ]
