# Generated by Django 4.2.7 on 2023-11-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_dailyweather_day_dailyweather_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweather',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='api.weatherinfo'),
        ),
        migrations.AlterField(
            model_name='hourlyweather',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly', to='api.weatherinfo'),
        ),
    ]
